# Etapa de desenvolvimento
FROM node:16 AS dev-frontend

# Define o diretório de trabalho
WORKDIR /app/frontend

# Copia o código-fonte do frontend
COPY frontend/ .

# Instala as dependências
RUN npm install

# Comando para rodar o servidor de desenvolvimento
CMD ["npm", "run", "serve"]
