version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - VUE_APP_NODE_ENV=${NODE_ENV}  # Variável para o Vue CLI
      - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}  # Passando a URL da API para o Vue 3
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env.local  # Você pode usar .env.local ou .env.production aqui também
