services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend 
      - /app/frontend/node_modules
    env_file:
      - frontend/.env.local


networks:
  app-network:
    driver: bridge